### ISSUE TITLE
Crashes server

### ISSUE THREAD

**Issue by Doedelsander** [Edivad99/SolarGeneration#1]
Hello,

I really like the mod, works fine in singleplayer but it keeps crashing when used on a server. 
Here is the crashlog: 
[crash-2019-08-31_17.17.41-server.txt](https://github.com/Edivad99/SolarGeneration/files/3562578/crash-2019-08-31_17.17.41-server.txt)

After removing this mod, the server was able to start up correctly.

(I am trying to add this to my modpack which contains just over 150 other mods.)

**Comment by Edivad99** [comment]
Thanks for reported it. I'll look at it now

**Comment by Edivad99** [comment]
Ok, I solved this problem. Time that curseforge approves the jar file and the update will be available for everyone

**Comment by Doedelsander** [comment]
Thank you very much!
