### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Lice2** [Edivad99/SolarGeneration#10]
---- Minecraft Crash Report ----
// You're mean.

Time: 07.10.19 12:32
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Solar Generation (solargeneration) encountered an error during the common_setup event phase
ยง7Attempted to load class net/minecraft/client/multiplayer/PlayerController for invalid dist DEDICATED_SERVER
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:198) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:151) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:46) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2289474528 bytes (2183 MB) / 2595225600 bytes (2475 MB) up to 3262644224 bytes (3111 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xms2500M -Xmx3500M
	ModLauncher: 4.0.0+61+ca3b447
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.36.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.36.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.36.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.36.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.36.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.36
	FML Language Providers: 
		javafml@28.1
		minecraft@1
		kotori_scala@2.13.1
	Mod List: 
		AdditionalEnchantedMiner-1.14.4-14.0.9.jar QuarryPlus {quarryplus@14.0.9 SIDED_SETUP}
		AI-Improvements-1.14.4-0.3.0.jar AI-Improvements {aiimprovements@0.2.2 SIDED_SETUP}
		Apotheosis-1.14.4-2.4.1.jar Apotheosis {apotheosis@2.4.1 SIDED_SETUP}
		BiomesOPlenty-1.14.4-9.0.0.254-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.254 SIDED_SETUP}
		ChineseWorkshop-1.14.4-2.3.0.jar ChineseWorkshop {chineseworkshop@2.3.0 SIDED_SETUP}
		create-mc1.14.4_v0.1.1.jar Create {create@0.1.1 SIDED_SETUP}
		Cucumber-1.14.4-2.0.3.jar Cucumber Library {cucumber@2.0.3 SIDED_SETUP}
		dankstorage-1.4b.jar Dank Storage {dankstorage@1.4b SIDED_SETUP}
		elevatorid-1.14.4-1.5.1.jar Elevator Mod {elevatorid@1.14.4-1.5.1 SIDED_SETUP}
		exp_bottling-1.14.4-3.jar EXP Bottling {exp_bottling@1.14.4-3 SIDED_SETUP}
		extdiamond-1.3.jar Extended Diamond {extdiamond@1.3 SIDED_SETUP}
		extlights-1.5.jar Extended Lights {extlights@1.5 SIDED_SETUP}
		furniture-7.0.0-pre10-1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre10 SIDED_SETUP}
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version SIDED_SETUP}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 SIDED_SETUP}
		IronJetpacks-1.14.4-2.0.2.jar Iron Jetpacks {ironjetpacks@2.0.2 SIDED_SETUP}
		jei-1.14.4-6.0.0.16.jar Just Enough Items {jei@6.0.0.16 SIDED_SETUP}
		Kiwi-1.14.4-2.3.3.jar Kiwi {kiwi@2.3.3 SIDED_SETUP}
		LargeFluidTank-14.8.2.jar FluidTank {fluidtank@14.8.2 SIDED_SETUP}
		luckyores-1.14.4-1.1.jar Lucky Ores Mod {luckyores@1.0 SIDED_SETUP}
		metalbarrels-1.3d.jar Metal Barrels {metalbarrels@1.3d SIDED_SETUP}
		mobcatcher-1.2b.jar Mob Catcher {mobcatcher@1.2b SIDED_SETUP}
		Morpheus-1.14.4-4.2.43.jar Morpheus {morpheus@version SIDED_SETUP}
		Neat+1.5-19.jar Neat {neat@1.5-19 SIDED_SETUP}
		OfflineSkins-1.14.4-v1.jar OfflineSkins {offlineskins@1.14.4-v1 SIDED_SETUP}
		Overloaded+Compressed+Blocks-1.14.4-1.0.8.jar Overloaded Compressed Blocks {overloaded_cb@1.14.4-1.0.8 SIDED_SETUP}
		Overloaded-1.14.4-0.0.76.jar Overloaded {overloaded@1.14.4-0.0.76 SIDED_SETUP}
		Placebo-1.14.4-2.3.1.jar Placebo {placebo@2.3.1 SIDED_SETUP}
		planttech2-0.01.03.jar PlantTech 2 {planttech2@0.01.03 SIDED_SETUP}
		portality-1.14.4-2.0.0-5f9c6a1.jar Portality {portality@NONE SIDED_SETUP}
		Redstone+Gear+Mod.jar Redstone Gear Mod {redstonegearmod@1.0 SIDED_SETUP}
		resynth-3.1.0.jar Resynth {resynth@3.1.0 SIDED_SETUP}
		Sauuuuucey's+Ores-1.14.4-1.3-release.jar Sauuuuucey's Ores {sauuuuuceysores@1.3-release SIDED_SETUP}
		SilentGear-1.14.4-1.4.2+67.jar Silent Gear {silentgear@1.4.2+67 SIDED_SETUP}
		SilentLib-1.14.4-4.4.0+44.jar Silent Lib {silentlib@4.4.0+44 SIDED_SETUP}
		SilentMechanisms-1.14.4-0.6.3+34.jar Silent's Mechanisms {silents_mechanisms@0.6.3+34 SIDED_SETUP}
		sisser-1.0.jar Sisser {sisser@1.0 SIDED_SETUP}
		SolarGeneration-1.14.4-1.0.2b.jar Solar Generation {solargeneration@1.0.2 ERROR}
		titanium-1.14.4-2.2.0-d9775a7.jar Titanium {titanium@1.14.4-2.2.0-d9775a7 SIDED_SETUP}
		tombstone-4.1.4-1.14.4.jar Corail Tombstone {tombstone@4.1.4 SIDED_SETUP}
		TreeChoppin-1.14.4-1.2.0.jar TreeChoppin {treechoppin@1.2.0 SIDED_SETUP}
		WesserboysOverlays-1.0.0.1-1.14.4.jar Wesserboy's Overlays {wesserboysoverlays@1.0.0.1 SIDED_SETUP}
		forge-1.14.4-28.1.36-universal.jar Forge {forge@28.1.36 SIDED_SETUP}
		forge-1.14.4-28.1.36-server.jar Minecraft {minecraft@1.14.4 SIDED_SETUP}
	Kiwi Modules: 
		chineseworkshop:blocks
		chineseworkshop:debug_stick
		chineseworkshop:decorations
		chineseworkshop:materials
		chineseworkshop:retexture
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Edivad99** [comment]
I will release an update this evening that will fix this issue

**Comment by Edivad99** [comment]
Ok, I fixed the bug, now it should start without problems. I already know of a bug that appears in the gui of the solar panel, I will solve it soon.
