### ISSUE TITLE
recipes in 1.14.4

### ISSUE THREAD

**Issue by daniel-for-github** [Edivad99/SolarGeneration#13]
mc 1.14.4
forge 28.1.45
SolarGeneration-1.14.4.-1.1.0

an we have no thermal foundation, there is no signalum etc.

as a workaround i had to modify the recipes inside the JAR
to use the material from silentMechanism

to be modified :
solar_core_hardened rom forge:nuggets/invar to forge:nuggets/iron
solar_core_redstone from forge:nuggets/electrum to forge:nuggets/gold
solar_core_signalum rom forge:nuggets/signalum to silents_mechanisms:copper_nugget
solar_core_resonant  from forge:nuggets/enderium to silents_mechanisms:silver_nugget
solar_core_advanced  from forge:nuggets/lumium to forge:storage_blocks/diamond
solar_core_ultimate from forge:nuggets/platinum to minecraft:nether_star

this is just my workaround to make it possible to play "real survivor"

you may have other recipes in mind , for next version(s), 
which have to come to fix the JEI intergration

but
good job, this the first WORKING solar mod for 1.14.4
I charge  rftoolpower powercells with the panels , works great

regards

**Comment by Edivad99** [comment]
What version of silentMechanism do you have?

**Comment by daniel-for-github** [comment]
SilentMechanisms-1.14.4-0.5.2+28.

**Comment by Edivad99** [comment]
You have to upgrade forge, the mod silent mechanism and restore the changes you've made to the solar generation

**Comment by Edivad99** [comment]
You're using an old version of the silent mechanism, with the new versions, all the ingots needed for my mod have been added.

**Comment by daniel-for-github** [comment]
Sorry, my fault, it took a while to figger out
had to update forge, silent mechanism and at least JEI  to be able to load my world.
will go back to unmodified solar mod.

did you count the resources, which are needed to get 1 ultimate panel
these are a couple of 100k each, so thats really endgame
