### ISSUE TITLE
[1.14.4] Display issue on the client side in the solar panel container with a dedicated server

### ISSUE THREAD

**Issue by HyCraftHD** [Edivad99/SolarGeneration#14]
The value wrappes around at 32000 into the minus values and up again. 
![grafik](https://user-images.githubusercontent.com/7681220/68965897-2f3e4b80-07dd-11ea-8f4b-73bfdb4e711a.png)

This is due to the trackInt method that casts the integer to a short value:
https://github.com/Edivad99/SolarGeneration/blob/38bb3a703bde2f2a82dda4bf4da4cbd1853c2ddd/src/main/java/edivad/solargeneration/blocks/containers/SolarPanelContainer.java#L26-L39

To fix this you must use custom packets like this custom tracker here: 
https://github.com/MC-U-Team/U-Team-Core/blob/153fd57f88a0d2d71a8f69072f86dc57a89970de/src/main/java/info/u_team/u_team_core/container/UContainer.java#L97-L103

**Comment by Edivad99** [comment]
Hi, I tried to look at your code, but since I'm still inexperienced, I can't understand much of it. If you want to help me it would be great.

**Comment by HyCraftHD** [comment]
No problem.
I make a pr soon.

**Comment by HyCraftHD** [comment]
Done. Your build system seems to bug though

**Comment by HyCraftHD** [comment]
Thanks fixed with #15
