### ISSUE TITLE
The message appears that a new update is available

### ISSUE THREAD

**Issue by Lice2** [Edivad99/SolarGeneration#16]
The message appears that a new update is available
Although the latest version is on the server and client.
And if you see the server as a client, it is displayed incompatible, but you can join. And then comes the message that a new update is available. but this is on server and client on it.
SolarGeneration-1.14.4-1.3.0
MineCraft 1.14.4
Forge :28.1.111

**Comment by Edivad99** [comment]
Really strange, the code that checks for updates hasn't been changed in the last few updates.  Was this bug also present in the previous version?

**Comment by Lice2** [comment]
No, there was never a hint. Or I was quick enough and always updated in time.

**Comment by Edivad99** [comment]
And once updated nothing came out?

**Comment by Edivad99** [comment]
Because probably even before there was the same problem

**Comment by Lice2** [comment]
There was a message for the first time in the version SolarGeneration-1.14.4-1.3.0.
But now the server shows that the mods do not match, but you can still connect.

**Comment by Edivad99** [comment]
But with SolarGeneration 1.2.1 did you have the same problem?

**Comment by Lice2** [comment]
No, there have never been any problems before.

**Comment by Lice2** [comment]
Maybe a Forge problem because I only updated Forge 28.1.111 two days ago.

**Comment by Edivad99** [comment]
I don't know what to say to you, hahahaha. If you look at the code that was modified / added with the last update you will notice that no changes have been made to the update check

**Comment by Lice2** [comment]
Hi, I have to apologize to you .... When I started Minecraft I somehow used my backup folder with the slightly older version of Solar Generation. Sorry I think it should work right away.

**Comment by Lice2** [comment]
I only noticed that when I added new mods and the number did not increase.
I hope you're not mad at me!
Greetings Lice

**Comment by Edivad99** [comment]
Don't worry I'm glad you solved it
