### ISSUE TITLE
[1.15.1] None of the Solar Cores have recipes.

### ISSUE THREAD

**Issue by Boomflex** [Edivad99/SolarGeneration#17]
Mod Version: SolarGeneration-1.15.1-1.0.0
Forge Version:  1.15.1 (modded) forge-30.0.35
Modpack: https://www.curseforge.com/minecraft/modpacks/just-not-enough-mods-2/files/2857047

No recipes showing for any Solar Cores meaning you can't currently craft them.

**Comment by Edivad99** [comment]
The recipes for creating solar panels work, unfortunately there are still no mods that implement ingots.  The creators of the modpack should change the recipes to make it playable
