### ISSUE TITLE
Crash when hooked up to fluxducts

### ISSUE THREAD

**Issue by Doedelsander** [Edivad99/SolarGeneration#2]
Hi,

Im back again.

I got the mod working, thanks for the quick fix! But I tried placing one down and hooking it up to an Energy Cell with a leadstone fluxduct but it didnt connect (Tried the T8, ultimate solar). Then tried with a Cryo-Stabilized Fluxduct but upon placing it, the server crashed. (If this mod was intended to be client sided only, then I'll remove it and stop using in on my server and wont bother you with server bugs.)

[crash-2019-08-31_22.04.45-server.txt](https://github.com/Edivad99/SolarGeneration/files/3562786/crash-2019-08-31_22.04.45-server.txt)

**Comment by Edivad99** [comment]
Ah, don't worry, since I don't have a minecraft server it is difficult for me to test the mo every time I release a version. Anyway if you can tell me these kind of errors. In fact, I noticed this bug and hope to solve it as soon as possible

**Comment by Edivad99** [comment]
Ok, I released an update. Please check if the issue was resolved.

**Comment by Doedelsander** [comment]
Works perfectly now. Thanks! If I find something else, I'll let you know.
