### ISSUE TITLE
Stacking Solar Panels do work? [1.12]

### ISSUE THREAD

**Issue by MrTK-Dev** [Edivad99/SolarGeneration#20]
I don't know if this is intended but the player may stack solar panels on top of each other and they still generate power.
![Desktop Screenshot 2020 03 21 - 17 27 41 21](https://user-images.githubusercontent.com/49124911/77231149-5e086c00-6b99-11ea-97ae-8e869f9d9798.png)

**Comment by Edivad99** [comment]
Hi, I was already aware of this bug, (other solar panel mods also have it). For 1.12.2 I will not release any other updates. It will be fixed in later versions.
