### ISSUE TITLE
[1.16.2] Crash when placed next to a block, that requests power

### ISSUE THREAD

**Issue by Cookie04DE** [Edivad99/SolarGeneration#22]
Hi, I encountered a crash, when trying to power a block of my mod, with one of your solar panels. Report: https://pastebin.com/Q1s03cCZ. I think there is a problem on your end, but I'm entirly sure.

**Comment by Cookie04DE** [comment]
Has this issue been resolved?

**Comment by Edivad99** [comment]
I can't reproduce your bug
