### ISSUE TITLE
[1.16.5-forge36.0.1] Error loading into server

### ISSUE THREAD

**Issue by ghost** [Edivad99/SolarGeneration#24]
IOException: Payload may not be larger than 1048576 bytes

no further messages of relevence in the logs sorry - it disconnects me with that message when I try to load into a server w/ this mod

**Comment by Edivad99** [comment]
I've done some test, but I can't reproduce your bug. Please send me your logs!

**Comment by ghost** [comment]
I think I just have too many mods in general as it appears after removing this mod and adding a few others.. I must've reached some kind of mc limit that all mods combine to send a packet for..
