### ISSUE TITLE
Not compatible with JEI

### ISSUE THREAD

**Issue by PtitCrissGaming** [Edivad99/SolarGeneration#28]
Can't see any receipe with JEI.. could be useful!

**Comment by Edivad99** [comment]
Read the description: 

> Since many ask me, "Why don't I see the recipes about JEI?". The answer is simple, the recipes use the oredictionary, this means that they accept all the minerals that add the other mods. So if you don't see the recipes, it means you don't have any mods that make this crafting possible.
