### ISSUE TITLE
Invalid recipes for 1.18.1

### ISSUE THREAD

**Issue by wanderingmage** [Edivad99/SolarGeneration#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

You have items in the recipes that are impossible to achieve because the mods they are from do not exist in 1.18.1.

### How can I reproduce this bug or crash?

1. Go to inventory
2. click on the solar cores in the JEI interface.
3. All solar cores from Hardened to Ultimate are impossible to create.

### Configuration

```markdown
- Mod version:4.0.0
- Forge version:39.1.2
- Minecraft version:1.18.1
```

**Comment by Edivad99** [comment]
It's not my problem

**Comment by wanderingmage** [comment]
It is your mod, correct?
You wrote the recipes, correct?
You decided to rely upon items from a mod that is no longer being updated, Correct?
I do believe that is the very definition of "your problem".

**Comment by Edivad99** [comment]
You're right, but I can't change recipes every time as I wait for someone to update their mod for a new version.

**Comment by ariosos** [comment]
It looks like most of these recipes are working now, except for Platinum nuggets (could be Iridium now?). Here's a suggestion, though - maybe have a "fallback recipe"? (I've seen other mods do this in the past - not a biggie, though, I could figure out kubejs and add a recipe myself).
i.e. -
Lead -> Raw Copper 
Invar -> Raw Iron
Electrum -> Raw Gold
Signalum -> Blaze Powder (or redstone?)
Enderium -> Ender Pearl
Lumium -> Glowstone Dust
Platinum -> Netherite Scrap

EDIT: Quick kubejs script (I modified an existing recipes.js file - put it at the end of the "onEvent(...) section). (Not sure why it doesn't actually remove the old recipe, though, but it works.) If you don't have FTB Industrial Contraptions, then you could substitute iridium for minecraft:netherite_scrap.

_// Solar Generation Fix
  event.remove({ id: "solargeneration:solar_core_ultimate" });
  event.shaped("solargeneration:solar_core_ultimate", [" I ","IAI"," I "], {
    I: "ftbic:iridium_nugget",
    A: "solargeneration:solar_core_advanced"
  });_

**Comment by Edivad99** [comment]
You can use this mod: https://www.curseforge.com/minecraft/mc-mods/orelibrary
