### ISSUE TITLE
The game freezes if you take the solar helmet in your hand.

### ISSUE THREAD

**Issue by rfin0** [Edivad99/SolarGeneration#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I was playing in my world with SolarGeneration and Iron Jetpacks mods installed, I decided to create a solar helmet, but as soon as I picked it up, the world froze along with the game. The solar helmet was not expected to cause any problems with the world or the game.

### How can I reproduce this bug or crash?

1. Create or enter any world. 
2. Find any entity to understand when the world is frozen. 
3. Take ANY solar helmet in your hand. 
4. Congratulations, you have frozen the world (and game).

### Configuration

```markdown
- Mod version: 7.0.0
- NeoForge version: 1.21.1 - 21.1.75
- Minecraft version: 1.21.1
```

### Relevant log output

```shell
https://mclo.gs/FFBWumf (there is no error in the logs)
```

### Anything else?

Video of the error reproduction (ONLY with SolarGeneration installed): https://www.youtube.com/watch?v=N4k26gF7tDA

**Comment by Gbergz** [comment]
Can confirm.

**Comment by Edivad99** [comment]
I released a version that fix this issue
