### ISSUE TITLE
How to craft a leadstone solar core?

### ISSUE THREAD

**Issue by ghost** [Edivad99/SolarGeneration#8]
When using JEI, the recipe of the leadstone solar core does not come out. Does it need to be found, crafted or both?

**Comment by Edivad99** [comment]
What version of Minecraft are you using?  If you are not using 1.12.2 it's normal that you do not see the recipes. For now there are very few mods that introduce the minerals needed for solar panels.

**Comment by ghost** [comment]
I am on Minecraft 1.14.4. Isn't it strange that your mod's dependency is stuck at 1.12.2 and your mod is at 1.14.4? Perhaps you could do a little bit of substitution?

**Comment by ghost** [comment]
You could use the lead nuggets in Slient's Mechanisms. I assume the recipe for the item is an iron ingot surrounded by lead nuggets, but not at the corners.

**Comment by Edivad99** [comment]
- The mod doesn't require thermal for 1.14.4 and 1.13.2. 
- I made a mistake in the solar core recipe file, I will release an update by today that will solve the problem. 
- The recipes however use forge's oredictionary, and do not base the crafting items mainly on a mod

As written in the description of curseforge **many mods that add minerals are not yet present in curseforge, so it is likely that some crafting will not be shown correctly on JEI.**

**Comment by Edivad99** [comment]
The update is available

**Comment by untidymaster** [comment]
Nice! May I close this issue?
